# Generated by Django 3.1.2 on 2020-12-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201205_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outputascii',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='report',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.TextField(max_length=1024),
        ),
    ]
