# Generated by Django 3.1.8 on 2021-07-11 08:53

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210418_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedascii',
            name='url_code',
            field=models.CharField(default=app.models.generate_url_code_for_generated_ascii_model, editable=False, max_length=6, unique=True),
        ),
    ]
